barbearia_teste:
  target: dev
  outputs:
    dev:
      type: duckdb
      # O prefixo 'md:' avisa que é MotherDuck
      # 'my_db' será o nome do banco lá na nuvem
      path: 'md:barbearia_db?token={{ env_var("MOTHERDUCK_TOKEN") }}' 
      threads: 1